from collections import Counter
from textgrid import TextGrid, IntervalTier
from .aligner import AlignerParser


class MausParser(AlignerParser):
    """
    Parser for TextGrids generated by the Web-MAUS aligner.
    """
    name = 'Maus'
    word_label = 'ort'
    phone_label = 'mau'

