[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_file = "polyglotdb/_version.py"

[tool.ruff]
line-length = 99

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
# E501: Line too long
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
# E402: Module level import not at top of file
"examples/**" = ["E402"]

[tool.check-manifest]
ignore = [
    ".deepsource.toml",
    ".readthedocs.yaml",
]

[tool.interrogate]
ignore-init-method = true
ignore-init-module = false
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-module = false
ignore-property-decorators = false
fail-under = 95
exclude = [
    "tests",
    "build",
    "dist",
    "setup.py",
    "docs"
]
verbose = 100
omit-covered-files = false
quiet = false
generate-badge = "docs/source/_static"
badge-format = "svg"
whitelist-regex = []
ignore-regex = []
color = true


[tool.coverage.report]
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
    "raise AssertionError",
    "raise NotImplementedError",
    "pass",
    "if sys.platform",
    "except ImportError:",
    "except KeyboardInterrupt:",
    "except Exception as e:",
    "except Exception:",
    "if call_back",
    "if is_set",
    "if TYPE_CHECKING:",
    "class ExitHooks(object):",
    "def main() -> None:",
    "if os.path.exists",
    "@abstractmethod",
]
fail_under = 50
