[build-system]
requires = ["setuptools>=77", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "polyglotdb"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "Montreal Corpus Tools", email = "michael.e.mcauliffe@gmail.com" }]
keywords = ["phonology", "corpus", "phonetics"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Topic :: Text Processing :: Linguistic",
]
dependencies = [
    "conch-sounds",
    "influxdb",
    "librosa",
    "neo4j",
    "praatio",
    "requests",
    "scipy",
    "tqdm",
    "pywin32; os_name == 'nt'",
]

[project.optional-dependencies]
dev = ["pre-commit", "pytest"]

[project.scripts]
pgdb = "polyglotdb.pgdb:main"

[project.urls]
Homepage = "https://github.com/MontrealCorpusTools/PolyglotDB"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
namespaces = false

[tool.setuptools.package-data]
polyglotdb = ["databases/*.conf", "polyglotdb/acoustics/formants/*.praat"]

[tool.setuptools_scm]
version_file = "polyglotdb/_version.py"

[tool.ruff]
line-length = 99

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
# E501: Line too long
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
# E402: Module level import not at top of file
"examples/**" = ["E402"]

[tool.check-manifest]
ignore = [
    ".deepsource.toml",
    ".readthedocs.yaml",
]

[tool.interrogate]
ignore-init-method = true
ignore-init-module = false
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-module = false
ignore-property-decorators = false
fail-under = 95
exclude = [
    "tests",
    "build",
    "dist",
    "docs"
]
verbose = 100
omit-covered-files = false
quiet = false
generate-badge = "docs/source/_static"
badge-format = "svg"
whitelist-regex = []
ignore-regex = []
color = true


[tool.coverage.report]
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
    "raise AssertionError",
    "raise NotImplementedError",
    "pass",
    "if sys.platform",
    "except ImportError:",
    "except KeyboardInterrupt:",
    "except Exception as e:",
    "except Exception:",
    "if call_back",
    "if is_set",
    "if TYPE_CHECKING:",
    "class ExitHooks(object):",
    "def main() -> None:",
    "if os.path.exists",
    "@abstractmethod",
]
fail_under = 50
