name: Build and publish to PyPI

on:
  push:
    branches: [main]
    tags: ["v*"]

jobs:
  python-version:
    uses: $/.github/workflows/python-version.yml
  build-n-publish:
    name: Build and publish to PyPI
    needs: python-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          # Always fetch entire history for setuptools-scm to work properly
          # https://setuptools-scm.readthedocs.io/latest/integrations/#troubleshooting
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ needs.python-version.outputs.min }}
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish to PyPI
        if: github.ref_type == 'tag'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
